- id: '1583779015997'
  alias: Entryway On
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 7938fe1dd207ee3736faa8823ccfb65e
    entity_id: binary_sensor.entryway_motion_occupancy
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - type: turn_on
    device_id: 1b4211ece672924db465a177f41b47c0
    entity_id: light.entryway_ceiling_light
    domain: light
  mode: single
- id: '1583779064247'
  alias: Entryway Off
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 7938fe1dd207ee3736faa8823ccfb65e
    entity_id: binary_sensor.entryway_motion_occupancy
    domain: binary_sensor
    for:
      hours: 0
      minutes: 3
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: 1b4211ece672924db465a177f41b47c0
    entity_id: light.entryway_ceiling_light
    domain: light
  mode: single
- id: '1583779363886'
  alias: Kitchen On
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 436e337219a560c2adab03e2b5f3adfe
    entity_id: binary_sensor.kitchen_motion_occupancy_2
    domain: binary_sensor
  condition: []
  action:
  - data: {}
    entity_id: light.kitchen_ceiling_light
    service: light.turn_on
  mode: single
- id: '1583779463844'
  alias: Kitchen Off
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 436e337219a560c2adab03e2b5f3adfe
    entity_id: binary_sensor.kitchen_motion_occupancy_2
    domain: binary_sensor
    for:
      hours: 0
      minutes: 3
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - data: {}
    entity_id: light.kitchen_ceiling_light
    service: light.turn_off
  mode: single
- id: '1583779540423'
  alias: Bathroom On
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: a4f2383bcfbe8c591541c16c4a2c4dc8
    entity_id: binary_sensor.bathroom_motion_occupancy
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - data: {}
    entity_id: light.bathroom_ceiling_light
    service: homeassistant.turn_on
  mode: single
- id: '1583779578603'
  alias: Bathroom Off
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: a4f2383bcfbe8c591541c16c4a2c4dc8
    entity_id: binary_sensor.bathroom_motion_occupancy
    domain: binary_sensor
    for:
      hours: 0
      minutes: 3
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - data: {}
    entity_id: light.bathroom_ceiling_light
    service: light.turn_off
  mode: single
- id: '1588458523846'
  alias: Toilet On
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: c436daa55f713ed43bdd0560caddbade
    entity_id: binary_sensor.toilet_motion_occupancy
    domain: binary_sensor
  condition: []
  action:
  - type: turn_on
    device_id: 1d8a6ec1c7a5d426c3bc0ae1d87f1a99
    entity_id: light.toilet_ceiling_light
    domain: light
  mode: single
- id: '1588458560538'
  alias: Toilet Off
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: c436daa55f713ed43bdd0560caddbade
    entity_id: binary_sensor.toilet_motion_occupancy
    domain: binary_sensor
    for:
      hours: 0
      minutes: 1
      seconds: 30
      milliseconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: 1d8a6ec1c7a5d426c3bc0ae1d87f1a99
    entity_id: light.toilet_ceiling_light
    domain: light
  mode: single
- id: '1627583365847'
  alias: Switch Living Room Right
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: b3088b50b410173785d231f94848e736
    type: click
    subtype: left
    discovery_id: 0x00158d0002ea052f click_left
  condition: []
  action:
  - type: toggle
    device_id: 29479a81ec41d0ce25c1ba0f97b30e20
    entity_id: light.living_room_ceiling_light
    domain: light
  mode: single
- id: '1627583474484'
  alias: Switch Living Room Left
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: b3088b50b410173785d231f94848e736
    type: click
    subtype: right
    discovery_id: 0x00158d0002ea052f click_right
  condition: []
  action:
  - type: toggle
    device_id: b0011ffa4c6d7fbb6d4727680a85af41
    entity_id: light.sideboard_light
    domain: light
  - type: toggle
    device_id: fe096adc4cbfb2c8d456b3ffc77f9cdf
    entity_id: light.picture_light
    domain: light
  mode: single
- id: '1627585994728'
  alias: Switch Office Right
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: a36e4c6eb68cf39cd66c5519c0496714
    type: click
    subtype: left
    discovery_id: 0x00158d0001e11856 click_left
  condition: []
  action:
  - type: toggle
    device_id: 2ec565972f0387f54e122d0d49667650
    entity_id: light.office_ceiling_light
    domain: light
  mode: single
- id: '1627586101347'
  alias: Switch Office Left
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: a36e4c6eb68cf39cd66c5519c0496714
    type: click
    subtype: right
    discovery_id: 0x00158d0001e11856 click_right
  condition: []
  action:
  - type: toggle
    device_id: 13b409959d2a200c69b392152fc6cd83
    entity_id: light.desk_light
    domain: light
  - service: light.toggle
    target:
      entity_id: light.screen_light
  mode: single
- id: '1637740184044'
  alias: Switch Bedroom Left
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: a2f7bce66e32953bfbe456309b5f911c
    type: click
    subtype: right
    discovery_id: 0x00158d0001f3f4cc click_right
  condition: []
  action:
  - type: toggle
    device_id: 3a54e5353f9562e7559702995f6e5a92
    entity_id: light.bed_light
    domain: light
  mode: single
- id: '1637740397600'
  alias: Switch Bedroom Right
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: a2f7bce66e32953bfbe456309b5f911c
    type: click
    subtype: left
    discovery_id: 0x00158d0001f3f4cc click_left
  condition: []
  action:
  - type: toggle
    device_id: 68398e4409a2d8f6c4cea705c2994c26
    entity_id: light.bedroom_ceiling_light
    domain: light
  mode: single
- id: '1638301817248'
  alias: Vacuum Daily
  description: ''
  trigger:
  - platform: time
    at: '10:00:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - device_id: 8c940ec4e1d315d6b30ae6c2ddcb8ab4
    domain: vacuum
    entity_id: vacuum.z10_pro
    type: clean
  mode: single
- id: '1645170931825'
  alias: Wash Notification
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.wash_plug_power
    above: '3'
    for:
      hours: 0
      minutes: 15
      seconds: 0
  condition: []
  action:
  - wait_for_trigger:
    - platform: numeric_state
      entity_id: sensor.wash_plug_power
      below: '2'
      for:
        hours: 0
        minutes: 5
        seconds: 0
  - service: notify.notify
    data:
      message: Washing machine done
  mode: single
