- id: '1583779015997'
  alias: Entryway On
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 7938fe1dd207ee3736faa8823ccfb65e
    entity_id: binary_sensor.entryway_motion_occupancy
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - type: turn_on
    device_id: 1b4211ece672924db465a177f41b47c0
    entity_id: light.entryway_ceiling_light
    domain: light
  mode: single
- id: '1583779064247'
  alias: Entryway Off
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 7938fe1dd207ee3736faa8823ccfb65e
    entity_id: binary_sensor.entryway_motion_occupancy
    domain: binary_sensor
    for:
      hours: 0
      minutes: 3
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: 1b4211ece672924db465a177f41b47c0
    entity_id: light.entryway_ceiling_light
    domain: light
  mode: single
- id: '1583779363886'
  alias: Kitchen On
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 436e337219a560c2adab03e2b5f3adfe
    entity_id: binary_sensor.kitchen_motion_occupancy
    domain: binary_sensor
  condition: []
  action:
  - data: {}
    entity_id: light.kitchen_ceiling_light
    service: light.turn_on
  mode: single
- id: '1583779463844'
  alias: Kitchen Off
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 436e337219a560c2adab03e2b5f3adfe
    entity_id: binary_sensor.kitchen_motion_occupancy
    domain: binary_sensor
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - data: {}
    entity_id: light.kitchen_ceiling_light
    service: light.turn_off
  mode: single
- id: '1583779540423'
  alias: Bathroom On
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: a4f2383bcfbe8c591541c16c4a2c4dc8
    entity_id: binary_sensor.bathroom_motion_occupancy
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.bathroom_mirror_light
  mode: single
- id: '1583779578603'
  alias: Bathroom Off
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: a4f2383bcfbe8c591541c16c4a2c4dc8
    entity_id: binary_sensor.bathroom_motion_occupancy
    domain: binary_sensor
    for:
      hours: 0
      minutes: 3
      seconds: 0
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      device_id: fe5f7df412ba5386cba5d75d536a5ea7
  mode: single
- id: '1588458523846'
  alias: Toilet On
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: c436daa55f713ed43bdd0560caddbade
    entity_id: binary_sensor.toilet_motion_occupancy
    domain: binary_sensor
  condition: []
  action:
  - type: turn_on
    device_id: 1d8a6ec1c7a5d426c3bc0ae1d87f1a99
    entity_id: light.toilet_ceiling_light
    domain: light
  mode: single
- id: '1588458560538'
  alias: Toilet Off
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: c436daa55f713ed43bdd0560caddbade
    entity_id: binary_sensor.toilet_motion_occupancy
    domain: binary_sensor
    for:
      hours: 0
      minutes: 1
      seconds: 30
      milliseconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: 1d8a6ec1c7a5d426c3bc0ae1d87f1a99
    entity_id: light.toilet_ceiling_light
    domain: light
  mode: single
- id: '1627583365847'
  alias: Switch Living Room Right
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: b3088b50b410173785d231f94848e736
    type: click
    subtype: left
    discovery_id: 0x00158d0002ea052f click_left
  condition: []
  action:
  - type: toggle
    device_id: 29479a81ec41d0ce25c1ba0f97b30e20
    entity_id: light.living_room_ceiling_light
    domain: light
  mode: single
- id: '1627583474484'
  alias: Switch Living Room Left
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: b3088b50b410173785d231f94848e736
    type: click
    subtype: right
    discovery_id: 0x00158d0002ea052f click_right
  condition: []
  action:
  - type: toggle
    device_id: 13b409959d2a200c69b392152fc6cd83
    entity_id: light.desk_light
    domain: light
  - type: toggle
    device_id: fe096adc4cbfb2c8d456b3ffc77f9cdf
    entity_id: light.picture_light
    domain: light
  - service: light.toggle
    data: {}
    target:
      entity_id: light.screen_light
  mode: single
- id: '1627585994728'
  alias: Switch Bedroom Right
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: a36e4c6eb68cf39cd66c5519c0496714
    type: click
    subtype: left
    discovery_id: 0x00158d0001e11856 click_left
  condition: []
  action:
  - type: toggle
    device_id: d0af96ad0a6e1204b4832c301cdbda50
    entity_id: light.bedroom_ceiling_light
    domain: light
  mode: single
- id: '1627586101347'
  alias: Switch Gym Left
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: a2f7bce66e32953bfbe456309b5f911c
    type: click
    subtype: right
    discovery_id: 0x00158d0001f3f4cc click_right
  condition: []
  action:
  - type: toggle
    device_id: 28661410a9549f4bb9a39af48b9ffac9
    entity_id: light.gym_ceiling_light
    domain: light
  mode: single
- id: '1637740184044'
  alias: Switch Bedroom Left
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: a36e4c6eb68cf39cd66c5519c0496714
    type: click
    subtype: right
    discovery_id: 0x00158d0001e11856 click_right
  condition: []
  action:
  - type: toggle
    device_id: d0af96ad0a6e1204b4832c301cdbda50
    entity_id: light.bedroom_ceiling_light
    domain: light
  mode: single
- id: '1637740397600'
  alias: Switch Gym Right
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: a2f7bce66e32953bfbe456309b5f911c
    type: click
    subtype: left
    discovery_id: 0x00158d0001f3f4cc click_left
  condition: []
  action:
  - type: toggle
    device_id: 28661410a9549f4bb9a39af48b9ffac9
    entity_id: light.gym_ceiling_light
    domain: light
  mode: single
- id: '1638301817248'
  alias: Vacuum Daily
  description: ''
  trigger:
  - platform: time
    at: '10:00:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    before: 00:00:00
  action:
  - device_id: 8c940ec4e1d315d6b30ae6c2ddcb8ab4
    domain: vacuum
    entity_id: vacuum.z10_pro
    type: clean
  mode: single
- id: '1645170931825'
  alias: Wash Notification
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.wash_power_energy_power
    above: '10'
    for:
      hours: 0
      minutes: 15
      seconds: 0
  condition: []
  action:
  - wait_for_trigger:
    - platform: numeric_state
      entity_id: sensor.wash_power_energy_power
      below: '10'
      for:
        hours: 0
        minutes: 3
        seconds: 0
  - service: notify.notify
    data:
      message: Washing machine done
  mode: single
- id: '1659884344918'
  alias: iOS Lights Off
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Lights Off
  condition: []
  action:
  - service: light.turn_off
    entity_id: light.all_lights
  mode: single
- id: '1659885384087'
  alias: iOS Start Vacuum
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Start Vacuum
  condition: []
  action:
  - device_id: 8c940ec4e1d315d6b30ae6c2ddcb8ab4
    domain: vacuum
    entity_id: vacuum.z10_pro
    type: clean
  mode: single
- id: '1659885423014'
  alias: iOS Stop Vacuum
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Stop Vacuum
  condition: []
  action:
  - device_id: 8c940ec4e1d315d6b30ae6c2ddcb8ab4
    domain: vacuum
    entity_id: vacuum.z10_pro
    type: dock
  mode: single
- id: '1659885712349'
  alias: iOS Lights On
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Lights On
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.all_lights
  mode: single
- id: '1659982431198'
  alias: Turn Off Alarm Light
  description: ''
  trigger:
  - platform: time
    at: 06:30:00
  condition: []
  action:
  - type: turn_off
    device_id: d0af96ad0a6e1204b4832c301cdbda50
    entity_id: light.bedroom_ceiling_light
    domain: light
  mode: single
- id: '1671466229446'
  alias: Switch Storage Left
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: b243065e805c40c0983fa92cf70e362b
    type: click
    subtype: right
    discovery_id: 0x00158d0002f08889 click_right
  condition: []
  action:
  - type: toggle
    device_id: 0996ec5c22094a3c1debbe14ec5fadb1
    entity_id: light.storage_ceiling_light
    domain: light
  mode: single
- id: '1671466594754'
  alias: Switch Storage Right
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: b243065e805c40c0983fa92cf70e362b
    type: click
    subtype: left
    discovery_id: 0x00158d0002f08889 click_left
  condition: []
  action:
  - type: toggle
    device_id: 0996ec5c22094a3c1debbe14ec5fadb1
    entity_id: light.storage_ceiling_light
    domain: light
  mode: single
