- id: '1583779015997'
  alias: Entryway On
  description: ''
  trigger:
  - device_id: b69e082bb69a4dd09024c325bc65398a
    domain: binary_sensor
    entity_id: binary_sensor.entryway_motion_aee42202_ias_zone
    for:
      hours: 0
      minutes: 0
      seconds: 0
    platform: device
    type: motion
  condition: []
  action:
  - device_id: 337d43e9503442b991d75334f75eef59
    domain: light
    entity_id: light.entryway_ceiling_light
    type: turn_on
  mode: single
- id: '1583779064247'
  alias: Entryway Off
  description: ''
  trigger:
  - device_id: b69e082bb69a4dd09024c325bc65398a
    domain: binary_sensor
    entity_id: binary_sensor.entryway_motion_aee42202_ias_zone
    for:
      hours: 0
      minutes: 3
      seconds: 0
    platform: device
    type: no_motion
  condition: []
  action:
  - device_id: 337d43e9503442b991d75334f75eef59
    domain: light
    entity_id: light.entryway_ceiling_light
    type: turn_off
  mode: single
- id: '1583779363886'
  alias: Kitchen On
  description: ''
  trigger:
  - device_id: 4ff6a258f1614075b7a28321835c796c
    domain: binary_sensor
    entity_id: binary_sensor.kitchen_motion_ias_zone
    platform: device
    type: motion
  condition: []
  action:
  - data: {}
    entity_id: light.kitchen_ceiling_light
    service: light.turn_on
  mode: single
- id: '1583779463844'
  alias: Kitchen Off
  description: ''
  trigger:
  - device_id: 4ff6a258f1614075b7a28321835c796c
    domain: binary_sensor
    entity_id: binary_sensor.kitchen_motion_ias_zone
    for:
      hours: 0
      minutes: 3
      seconds: 0
    platform: device
    type: no_motion
  condition: []
  action:
  - data: {}
    entity_id: light.kitchen_ceiling_light
    service: light.turn_off
  mode: single
- id: '1583779540423'
  alias: Bathroom On
  description: ''
  trigger:
  - device_id: 011d2b04ae864e34bb702c4aa6eb9669
    domain: binary_sensor
    entity_id: binary_sensor.bathroom_motion_ias_zone
    platform: device
    type: motion
  condition: []
  action:
  - data: {}
    entity_id: light.bathroom_ceiling_light
    service: homeassistant.turn_on
  mode: single
- id: '1583779578603'
  alias: Bathroom Off
  description: ''
  trigger:
  - device_id: 011d2b04ae864e34bb702c4aa6eb9669
    domain: binary_sensor
    entity_id: binary_sensor.bathroom_motion_ias_zone
    for:
      hours: 0
      minutes: 3
      seconds: 0
    platform: device
    type: no_motion
  condition: []
  action:
  - data: {}
    entity_id: light.bathroom_ceiling_light
    service: light.turn_off
  mode: single
- id: '1588458523846'
  alias: Toilet On
  description: ''
  trigger:
  - device_id: 5f5b7434c79941b4bd0c43d63718d24c
    domain: binary_sensor
    entity_id: binary_sensor.toilet_motion_ias_zone
    platform: device
    type: motion
  condition: []
  action:
  - device_id: 56a12ef92607411e89f42477605f0542
    domain: light
    entity_id: light.toilet_light
    type: turn_on
  mode: single
- id: '1588458560538'
  alias: Toilet Off
  description: ''
  trigger:
  - device_id: 5f5b7434c79941b4bd0c43d63718d24c
    domain: binary_sensor
    entity_id: binary_sensor.toilet_motion_ias_zone
    platform: device
    type: no_motion
  condition: []
  action:
  - device_id: 56a12ef92607411e89f42477605f0542
    domain: light
    entity_id: light.toilet_light
    type: turn_off
  mode: single
