homeassistant:
    name: Home
    latitude: !secret home_lat
    longitude: !secret home_long
    elevation: !secret home_elev
    unit_system: metric
    time_zone: !secret home_time
    customize: !include customize.yaml

frontend:
    themes: !include themes.yaml

# Enables configuration UI
config:
system_health:
mobile_app:

google_assistant:
    project_id: ga_project_id
    service_account: !include google_assistant.json
    exposed_domains:
        - light
        - switch
    entity_config:
        light.conbee:
            expose: false
        light.conbee2:
            expose: false

tado:
  username: !secret tado_username
  password: !secret tado_password

http:
    base_url: !secret base_url

updater:

lovelace:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include sensor.yaml
light: !include light.yaml
yeelight: !include yeelight.yaml
switch: !include switch.yaml

mqtt:
    broker: !secret mqtt_host
    username: !secret mqtt_username
    password: !secret mqtt_password

