homeassistant:
    name: Home
    latitude: !secret home_lat
    longitude: !secret home_long
    elevation: !secret home_elev
    unit_system: metric
    time_zone: !secret home_time
    customize: !include customize.yaml

frontend:
    themes: !include themes.yaml

# Enables configuration UI
config:
system_health:
google_assistant:
    project_id: ga_project_id
    api_key: ga_api_key
    exposed_domains:
        - switch
        - light
        - script

http:
    base_url: !secret base_url

updater:

# Discover some devices automatically
discovery:
    ignore:
        - plex_mediaserver
        - yeelight
        - igd
        - yeelight

lovelace:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include sensor.yaml
light: !include light.yaml
yeelight: !include yeelight.yaml
switch: !include switch.yaml

panel_iframe:
    deconz:
        title: "Deconz"
        url: "https://deconz.gempir.com"
        icon: "mdi:router-wireless"

mqtt:
    broker: !secret mqtt_host
    username: !secret mqtt_username
    password: !secret mqtt_password
