homeassistant:
    name: Home
    latitude: !secret home_lat
    longitude: !secret home_long
    elevation: !secret home_elev
    unit_system: metric
    time_zone: !secret home_time
    customize: !include customize.yaml

frontend:
    themes: !include themes.yaml

config:
system_health:
mobile_app:
http:
    cors_allowed_origins:
        - https://google.com
        - https://www.home-assistant.io
    use_x_forwarded_for: true
    trusted_proxies:
        - 172.19.0.1
        - 192.168.178.40
    ip_ban_enabled: true
    login_attempts_threshold: 10

google_assistant: !include google_assistant.yaml


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include sensor.yaml
mqtt: !include mqtt.yaml
yeelight: !include yeelight.yaml
switch: !include switch.yaml
prometheus:

