homeassistant:
    name: Home
    latitude: !secret home_lat
    longitude: !secret home_long
    elevation: !secret home_elev
    unit_system: metric
    time_zone: !secret home_time
    customize: !include customize.yaml

frontend:
    themes: !include themes.yaml

# Enables configuration UI
config:
system_health:
google_assistant:
  project_id: ga_project_id
  api_key: ga_api_key
  exposed_domains:
    - switch
    - light
    - script
            
http:
    # Secrets are defined in the file secrets.yaml
    api_password: !secret http_password
    # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
    base_url: !secret base_url


updater:

# Discover some devices automatically
discovery:
    ignore:
    - plex_mediaserver
    - yeelight
    - igd
    - yeelight

# Text to speech
tts:
    - platform: google
    
lovelace:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include sensor.yaml
light: !include light.yaml
yeelight: !include yeelight.yaml
switch: !include switch.yaml

panel_iframe:
    configurator:
        title: Configurator
        icon: mdi:wrench
        url: !secret configurator

mqtt:  
    broker: 127.0.0.1
    username: !secret mqtt_username
    password: !secret mqtt_password
