homeassistant:
    name: Home
    latitude: !secret home_lat
    longitude: !secret home_long
    elevation: !secret home_elev
    unit_system: metric
    time_zone: !secret home_time
    customize: !include customize.yaml

frontend:
    themes: !include themes.yaml

# Enables configuration UI
config:
system_health:
mobile_app:

google_assistant:
    project_id: ga_project_id
    service_account: !include google_assistant.json
    exposed_domains:
        - light
        - switch
        - vacuum
    entity_config:
        light.conbee:
            expose: false
        light.conbee2:
            expose: false

http:
    cors_allowed_origins:
        - https://google.com
        - https://www.home-assistant.io
    use_x_forwarded_for: true
    trusted_proxies:
        - 10.0.0.200
        - 172.17.0.1
        - 192.168.178.40
        - 172.30.33.0/24
    ip_ban_enabled: true
    login_attempts_threshold: 10

updater:

lovelace:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include sensor.yaml
light: !include light.yaml
yeelight: !include yeelight.yaml
switch: !include switch.yaml
influxdb: !include influxdb.yaml
prometheus:

mqtt:
    broker: !secret mqtt_host
    username: !secret mqtt_username
    password: !secret mqtt_password

