- platform: mqtt
  schema: json
  name: Falcon Light
  state_topic: "home/falcon"
  command_topic: "home/falcon/set"
  brightness: true
  rgb: true
  optimistic: false
  qos: 0
- platform: "mqtt"
  name: Office Light
  state_topic: "zigbee2mqtt/0x000b57fffe0ee020"
  availability_topic: "zigbee2mqtt/bridge/state"
  brightness: true
  schema: "json"
  command_topic: "zigbee2mqtt/0x000b57fffe0ee020/set"
- platform: "mqtt"
  name: Storage Ceiling Light
  state_topic: "zigbee2mqtt/0x000b57fffe260d2b"
  availability_topic: "zigbee2mqtt/bridge/state"
  brightness: true
  schema: "json"
  command_topic: "zigbee2mqtt/0x000b57fffe260d2b/set"
- platform: "mqtt"
  name: Toilet Ceiling Light
  state_topic: "zigbee2mqtt/0x000b57fffe2de8b4"
  availability_topic: "zigbee2mqtt/bridge/state"
  brightness: true
  schema: "json"
  command_topic: "zigbee2mqtt/0x000b57fffe2de8b4/set"
- platform: "mqtt"
  name: Bedroom Ceiling Light
  state_topic: "zigbee2mqtt/0x000b57fffe161262"
  availability_topic: "zigbee2mqtt/bridge/state"
  brightness: true
  schema: "json"
  command_topic: "zigbee2mqtt/0x000b57fffe161262/set"
- platform: "mqtt"
  name: Entryway Ceiling Light
  state_topic: "zigbee2mqtt/0x000b57fffe2689c7"
  availability_topic: "zigbee2mqtt/bridge/state"
  brightness: true
  schema: "json"
  command_topic: "zigbee2mqtt/0x000b57fffe2689c7/set"
  
