# Dimmers
- platform: "mqtt"
  state_topic: "zigbee2mqtt/0x000b57fffe11bce6"
  name: office_dimmer
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "brightness"
  icon: "mdi:brightness-5"
  value_template: "{{ value_json.brightness }}"
  json_attributes: 
  - "linkquality"
- platform: "mqtt"
  state_topic: "zigbee2mqtt/0x000b57fffe2543e4"
  name: entryway_dimmer
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "brightness"
  icon: "mdi:brightness-5"
  value_template: "{{ value_json.brightness }}"
  json_attributes: 
  - "linkquality"
- platform: "mqtt"
  state_topic: "zigbee2mqtt/0x000b57fffe24269f"
  name: storage_dimmer
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "brightness"
  icon: "mdi:brightness-5"
  value_template: "{{ value_json.brightness }}"
  json_attributes: 
  - "linkquality"


# Wallswitches
- platform: "mqtt"
  name: office_switch
  state_topic: "zigbee2mqtt/0x00158d0001e11856"
  availability_topic: "zigbee2mqtt/bridge/state"
  icon: "mdi:toggle-switch"
  value_template: "{{ value_json.click }}"
  json_attributes: 
  - "linkquality"
  - "battery"
  - "voltage"
  - "action"
  - "duration"
  force_update: true
- platform: "mqtt"
  name: bedroom_switch
  state_topic: "zigbee2mqtt/0x00158d0001f3f4cc"
  availability_topic: "zigbee2mqtt/bridge/state"
  icon: "mdi:toggle-switch"
  value_template: "{{ value_json.click }}"
  json_attributes: 
  - "linkquality"
  - "battery"
  - "voltage"
  - "action"
  - "duration"
  force_update: true