- platform: broadlink
  host: 192.168.178.35
  mac: '34:EA:34:40:A5:DA'
  switches:
      tv:
          command_on: 'JgAYAZOVETkSORE6ERQSFBEVERQRFRE6ETkROhEVERQRFREUEhQRFRE5EToRFREUEToROhE5EToRFREUEToROhEUERURFREABe2UlBM4EzcUNxMTExIUEhMTExIUNxM3FDcUEhMSFBITExMSFBITNxQ3FBITExM3FDcTOBM3FBITExM3FDcTExMSFBITAAXrlJQUNxM4EzcUEhMTExIUEhMSFDcUNxM3FBIUEhMSFBITExMSFDcTNxQSFBITNxQ3FDcTNxQSFBITNxQ3FBITEhQSEwAF65WTFDcUNxM3FBIUEhMSFBITExM3FDcTOBMSFBITExMSFBITEhQ3FDcTEhQSEzgTNxQ3FDcTEhQSEzgTNxQSExMTEhQADQU='            
          command_off: 'JgAYAZOVETkSORE6ERQSFBEVERQRFRE6ETkROhEVERQRFREUEhQRFRE5EToRFREUEToROhE5EToRFREUEToROhEUERURFREABe2UlBM4EzcUNxMTExIUEhMTExIUNxM3FDcUEhMSFBITExMSFBITNxQ3FBITExM3FDcTOBM3FBITExM3FDcTExMSFBITAAXrlJQUNxM4EzcUEhMTExIUEhMSFDcUNxM3FBIUEhMSFBITExMSFDcTNxQSFBITNxQ3FDcTNxQSFBITNxQ3FBITEhQSEwAF65WTFDcUNxM3FBIUEhMSFBITExM3FDcTOBMSFBITExMSFBITEhQ3FDcTEhQSEzgTNxQ3FDcTEhQSEzgTNxQSExMTEhQADQU='
      soundbar:
          command_on: 'JgBYAAABKJMTEhMSExITNxM2FDYTNxMSEzcTNxM2FBEUEhMSExITNhQSExITNhQ2ExITEhM3EzcTNxM2FBITEhM2EzcTEhMSEwAFCgABKEoTAAxBAAEoShMADQU='
          command_off: 'JgBYAAABKJMTEhMSExITNxM2FDYTNxMSEzcTNxM2FBEUEhMSExITNhQSExITNhQ2ExITEhM3EzcTNxM2FBITEhM2EzcTEhMSEwAFCgABKEoTAAxBAAEoShMADQU='
      xbox:
          command_on: 'JgBIAAABKpQTERMTEhMTEhMSExITEhM4EhMTERMTEzcTNxMSEzgTNxMSExITNxMSExMTNxM3ExITOBI4ExITOBI3ExMTEhE5EwANBQ=='
          command_off: 'JgBQAAABKJQTEhQSExIUEhMSFBITEhM3FBITEhQSEzcUNxMSEzgTNxM3FBITEhQ3ExITOBMSExIUEhM3FDcTEhM3FBITNxQ3EwAFnwABKUkTAA0FAAAAAAAAAAA='