title: Daniel's Home

views:
  - title: Home
    id: home
    icon: mdi:home
    cards:
      - type: entities
        title: Living Room
        show_header_toggle: false
        entities:
          - light.living_room_light
          - light.couch_light
          - light.falcon_light
          - type: divider
            style: 
              border-top: 1px solid #EEEEEE
          - switch.zeus
          - switch.receiver
          - switch.xbox
      - type: entities
        title: Office
        show_header_toggle: false
        entities:
          - light.office_light
      - type: entities
        title: Bedroom
        show_header_toggle: false
        entities:
          - light.bed_light
      - type: entities
        title: Kitchen
        show_header_toggle: false
        entities:
          - light.kitchen_light
          - light.gateway_light_7811dcb2249f
      - type: entities
        title: Bathroom
        show_header_toggle: false
        entities:
          - light.bathroom_light

  - icon: mdi:play
    title: Media
    cards:
      - type: entities
        title: Players
        entities:
          - media_player.spotify
          - media_player.office
          - media_player.living_room
          - media_player.bedroom
          - media_player.chromecast5898